### ISSUE TITLE
libtraceroute: unable to create util: No such file or directory 

### ISSUE THREAD

**Issue by MikeChongCan** [ilyagrishkov/libtraceroute#23]
```
thread 'main' panicked at 'libtraceroute: unable to create util: No such file or directory (os error 2)', /Users/[username]/.cargo/registry/src/github.com-1ecc6299db9ec823/libtraceroute-0.1.0/src/util/mod.rs:115:23
stack backtrace:
   0: rust_begin_unwind
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:498:5
   1: core::panicking::panic_fmt
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/panicking.rs:116:14
   2: libtraceroute::util::Channel::send_to
             at /Users/[username]/.cargo/registry/src/github.com-1ecc6299db9ec823/libtraceroute-0.1.0/src/util/mod.rs:115:23
   3: libtraceroute::Traceroute::get_next_query_result
             at /Users/[username]/.cargo/registry/src/github.com-1ecc6299db9ec823/libtraceroute-0.1.0/src/lib.rs:253:9
   4: libtraceroute::Traceroute::calculate_next_hop
             at /Users/[username]/.cargo/registry/src/github.com-1ecc6299db9ec823/libtraceroute-0.1.0/src/lib.rs:238:26
   5: <libtraceroute::Traceroute as core::iter::traits::iterator::Iterator>::next
thread 'main' panicked at 'libtraceroute: unable to create util: No such file or directory (os error 2)', /Users/[username]/.cargo/registry/src/github.com-1ecc6299db9ec823/libtraceroute-0.1.0/src/util/mod.rs:115:23
stack backtrace:
   0: rust_begin_unwind
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:498:5
   1: core::panicking::panic_fmt
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/panicking.rs:116:14
   2: libtraceroute::util::Channel::send_to
             at /Users/[username]/.cargo/registry/src/github.com-1ecc6299db9ec823/libtraceroute-0.1.0/src/util/mod.rs:115:23
   3: libtraceroute::Traceroute::get_next_query_result
             at /Users/[username]/.cargo/registry/src/github.com-1ecc6299db9ec823/libtraceroute-0.1.0/src/lib.rs:253:9
   4: libtraceroute::Traceroute::calculate_next_hop
             at /Users/[username]/.cargo/registry/src/github.com-1ecc6299db9ec823/libtraceroute-0.1.0/src/lib.rs:238:26
   5: <libtraceroute::Traceroute as core::iter::traits::iterator::Iterator>::next
             at /Users/[username]/.cargo/registry/src/github.com-1ecc6299db9ec823/libtraceroute-0.1.0/src/lib.rs:201:19
   6: route_tracer::main
             at ./src/main.rs:11:16
   7: core::ops::function::FnOnce::call_once
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

Environment:

```shell
rustc 1.59.0 (9d1b2106e 2022-02-23)
cargo 1.59.0 (49d8809dc 2022-02-10)
```

I just ran the example code: <https://github.com/ilyagrishkov/libtraceroute/blob/master/examples/simple_traceroute.rs> but it panicked.
Any thoughts?

**Comment by horochx** [comment]
Are you using macOS? I had the same question, and found the answer in [libpnet #82](https://github.com/libpnet/libpnet/issues/82). But I don't know how to solve the permissions problem, `sudo chmod /dev/bpf*` doesn't work for me. So I'm currently running in privileged mode.
